//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 最前面画像ミギシタ.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("最前面画像ミギシタ.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   バージョン：1.0 
        ///作成者：SKA 
        /// 
        ///© 2018 SKA 
        /// 
        ///商用での無断転載（2次配布）および 商用での無断改変はご遠慮ください。 
        ///Twitter：@SK_Animation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonInput {
            get {
                return ResourceManager.GetString("ButtonInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ButtonRun {
            get {
                return ResourceManager.GetString("ButtonRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像ファイルを認識できませんでした。
        ///ファイルを確認するか別の画像で試してみてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cannotImport {
            get {
                return ResourceManager.GetString("cannotImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右下 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComboBoxItem1 {
            get {
                return ResourceManager.GetString("ComboBoxItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右上 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComboBoxItem2 {
            get {
                return ResourceManager.GetString("ComboBoxItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左上 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComboBoxItem3 {
            get {
                return ResourceManager.GetString("ComboBoxItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左下 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComboBoxItem4 {
            get {
                return ResourceManager.GetString("ComboBoxItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中央 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ComboBoxItem5 {
            get {
                return ResourceManager.GetString("ComboBoxItem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー (_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 (_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了する (_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル (_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ (_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像入力： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelInput {
            get {
                return ResourceManager.GetString("LabelInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示位置： に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LabelPosition {
            get {
                return ResourceManager.GetString("LabelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像を開く (_O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ⚙設定 (_O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はりつけっ！ (_P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実行する (_R) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示する画像ファイルを指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string specifyImage {
            get {
                return ResourceManager.GetString("specifyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像ファイルまたは表示位置を取得できませんでした。
        ///もう一度やり直してみてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tryAgain {
            get {
                return ResourceManager.GetString("tryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最前面画像ミギシタ について (_A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最前面画像ミギシタ について に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Version2 {
            get {
                return ResourceManager.GetString("Version2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Window1 {
            get {
                return ResourceManager.GetString("Window1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最前面画像ミギシタ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Window2 {
            get {
                return ResourceManager.GetString("Window2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string 日本語 {
            get {
                return ResourceManager.GetString("日本語", resourceCulture);
            }
        }
    }
}
